version: '3.3'
services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    working_dir: /app
    restart: always
    volumes:
      - ../app:/app # Каталог приложения
      - ./php/config/php.ini:/usr/local/etc/php/php.ini:ro # конфиг php
      - ~/.ssh/:/root/.ssh/ # ключи ssh проброшены в контейнер для работы с репозиториями зависимостей
    ports:
      - 80:80
  db:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_MY_DATABASE: db
      TZ: "Europe/Moscow"
    volumes:
      - ./mysql/db/:/var/lib/mysql/
    ports:
      - 3306:3306